# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ice_config.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ice_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ice_config.proto\x12\x1c\x61ndroid.emulation.control.v2\x1a\x1egoogle/protobuf/duration.proto\"\xc7\x02\n\rIceServerList\x12\x0c\n\x04urls\x18\x01 \x03(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x12\n\ncredential\x18\x03 \x01(\t\x12J\n\x0ftls_cert_policy\x18\x04 \x01(\x0e\x32\x31.android.emulation.control.v2.TlsCertPolicy.Value\x12\x10\n\x08hostname\x18\x05 \x01(\t\x12\x1a\n\x12tls_alpn_protocols\x18\x06 \x03(\t\x12\x1b\n\x13tls_elliptic_curves\x18\x07 \x03(\t\x12N\n\x0estun_alt_magic\x18\t \x01(\x0e\x32\x36.android.emulation.control.v2.StunAltMagicSetting.Type\x12\x15\n\rmax_rate_kbps\x18\n \x01(\x03J\x04\x08\x08\x10\t\"\x89\x03\n\x0fIceServerConfig\x12\x34\n\x11lifetime_duration\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\x12@\n\x0bice_servers\x18\x02 \x03(\x0b\x32+.android.emulation.control.v2.IceServerList\x12\x1c\n\x14ice_transport_policy\x18\x06 \x01(\t\x12\x45\n\x0c\x62lock_status\x18\x03 \x01(\x0e\x32/.android.emulation.control.v2.BlockStatus.Value\x12H\n\x13unblock_ice_servers\x18\x04 \x03(\x0b\x32+.android.emulation.control.v2.IceServerList\x12\x43\n\x0eunblock_config\x18\x07 \x01(\x0b\x32+.android.emulation.control.v2.UnblockConfigJ\x04\x08\x05\x10\x06J\x04\x08\x08\x10\t\"\x99\x01\n\rUnblockConfig\x12\x16\n\x0emin_pad_length\x18\x01 \x01(\x05\x12\x16\n\x0emax_pad_length\x18\x02 \x01(\x05\x12%\n\x1dmin_channel_data_payload_size\x18\x03 \x01(\x05\x12\x19\n\x11pad_ice_stun_ping\x18\x04 \x01(\x08\x12\x16\n\x0e\x65nable_padding\x18\x05 \x01(\x08\"U\n\x0b\x42lockStatus\"F\n\x05Value\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x0f\n\x0bNOT_BLOCKED\x10\x01\x12\x14\n\x10POSSIBLY_BLOCKED\x10\x02\"C\n\rTlsCertPolicy\"2\n\x05Value\x12\x12\n\x0e\x44\x45\x46\x41ULT_SECURE\x10\x00\x12\x15\n\x11INSECURE_NO_CHECK\x10\x01\"E\n\x13StunAltMagicSetting\".\n\x04Type\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x0c\n\x08\x44ISABLED\x10\x01\x12\x0b\n\x07\x45NABLED\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ice_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ICESERVERLIST']._serialized_start=83
  _globals['_ICESERVERLIST']._serialized_end=410
  _globals['_ICESERVERCONFIG']._serialized_start=413
  _globals['_ICESERVERCONFIG']._serialized_end=806
  _globals['_UNBLOCKCONFIG']._serialized_start=809
  _globals['_UNBLOCKCONFIG']._serialized_end=962
  _globals['_BLOCKSTATUS']._serialized_start=964
  _globals['_BLOCKSTATUS']._serialized_end=1049
  _globals['_BLOCKSTATUS_VALUE']._serialized_start=979
  _globals['_BLOCKSTATUS_VALUE']._serialized_end=1049
  _globals['_TLSCERTPOLICY']._serialized_start=1051
  _globals['_TLSCERTPOLICY']._serialized_end=1118
  _globals['_TLSCERTPOLICY_VALUE']._serialized_start=1068
  _globals['_TLSCERTPOLICY_VALUE']._serialized_end=1118
  _globals['_STUNALTMAGICSETTING']._serialized_start=1120
  _globals['_STUNALTMAGICSETTING']._serialized_end=1189
  _globals['_STUNALTMAGICSETTING_TYPE']._serialized_start=1143
  _globals['_STUNALTMAGICSETTING_TYPE']._serialized_end=1189
# @@protoc_insertion_point(module_scope)
