# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rtc_service_v2_pb2 as rtc__service__v2__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rtc_service_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RtcStub:
    """An RTC service lets you interact with the emulator through WebRTC
    Note that this is currently an experimental feature, and that the
    service definition might change without notice. Use at your own risk!

    The following endpoints are needed to establish the webrtc protocol
    Due to limitiations in Javascript we cannot make use of bidirectional
    endpoints See this [blog](https://grpc.io/blog/state-of-grpc-web) for
    details.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestRtcStream = channel.unary_unary(
                '/android.emulation.control.v2.Rtc/RequestRtcStream',
                request_serializer=rtc__service__v2__pb2.RtcStreamRequest.SerializeToString,
                response_deserializer=rtc__service__v2__pb2.RtcStreamResponse.FromString,
                _registered_method=True)
        self.SendJsepMessage = channel.unary_unary(
                '/android.emulation.control.v2.Rtc/SendJsepMessage',
                request_serializer=rtc__service__v2__pb2.SendJsepMessageRequest.SerializeToString,
                response_deserializer=rtc__service__v2__pb2.SendJsepMessageResponse.FromString,
                _registered_method=True)
        self.ReceiveJsepMessageStream = channel.unary_stream(
                '/android.emulation.control.v2.Rtc/ReceiveJsepMessageStream',
                request_serializer=rtc__service__v2__pb2.ReceiveJsepMessageRequest.SerializeToString,
                response_deserializer=rtc__service__v2__pb2.ReceiveJsepMessageResponse.FromString,
                _registered_method=True)
        self.ReceiveJsepMessage = channel.unary_unary(
                '/android.emulation.control.v2.Rtc/ReceiveJsepMessage',
                request_serializer=rtc__service__v2__pb2.ReceiveJsepMessageRequest.SerializeToString,
                response_deserializer=rtc__service__v2__pb2.ReceiveJsepMessageResponse.FromString,
                _registered_method=True)


class RtcServicer:
    """An RTC service lets you interact with the emulator through WebRTC
    Note that this is currently an experimental feature, and that the
    service definition might change without notice. Use at your own risk!

    The following endpoints are needed to establish the webrtc protocol
    Due to limitiations in Javascript we cannot make use of bidirectional
    endpoints See this [blog](https://grpc.io/blog/state-of-grpc-web) for
    details.
    """

    def RequestRtcStream(self, request, context):
        """This function will generate a new identifier that the client
        should use for further interaction. It will initiate the
        JSEP protocol on the server side.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendJsepMessage(self, request, context):
        """Sends the given JsepMsg to the server. The RtcId in the
        message should point to an active stream negotiation in
        progress, otherwise the message will be ignored.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveJsepMessageStream(self, request, context):
        """Reads an available jsep messages for the given client id,
        blocking until one becomes available. Do not use the polling version
        above if you opt for this one.

        The ice candidates for example will trickle in on this callback,
        as will the SDP negotation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveJsepMessage(self, request, context):
        """[DEPRECATED] This is only here as the go grpc webproxy used
        by fuchsia does not support server side streaming. This method
        will be removed in the future and should not be relied upon.

        Reads an available jsep messages for the given client id,
        blocking until one becomes available. Do not use the polling version
        above if you opt for this one.

        The ice candidates for example will trickle in on this callback,
        as will the SDP negotation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RtcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestRtcStream': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRtcStream,
                    request_deserializer=rtc__service__v2__pb2.RtcStreamRequest.FromString,
                    response_serializer=rtc__service__v2__pb2.RtcStreamResponse.SerializeToString,
            ),
            'SendJsepMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendJsepMessage,
                    request_deserializer=rtc__service__v2__pb2.SendJsepMessageRequest.FromString,
                    response_serializer=rtc__service__v2__pb2.SendJsepMessageResponse.SerializeToString,
            ),
            'ReceiveJsepMessageStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceiveJsepMessageStream,
                    request_deserializer=rtc__service__v2__pb2.ReceiveJsepMessageRequest.FromString,
                    response_serializer=rtc__service__v2__pb2.ReceiveJsepMessageResponse.SerializeToString,
            ),
            'ReceiveJsepMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveJsepMessage,
                    request_deserializer=rtc__service__v2__pb2.ReceiveJsepMessageRequest.FromString,
                    response_serializer=rtc__service__v2__pb2.ReceiveJsepMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'android.emulation.control.v2.Rtc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('android.emulation.control.v2.Rtc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Rtc:
    """An RTC service lets you interact with the emulator through WebRTC
    Note that this is currently an experimental feature, and that the
    service definition might change without notice. Use at your own risk!

    The following endpoints are needed to establish the webrtc protocol
    Due to limitiations in Javascript we cannot make use of bidirectional
    endpoints See this [blog](https://grpc.io/blog/state-of-grpc-web) for
    details.
    """

    @staticmethod
    def RequestRtcStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.emulation.control.v2.Rtc/RequestRtcStream',
            rtc__service__v2__pb2.RtcStreamRequest.SerializeToString,
            rtc__service__v2__pb2.RtcStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendJsepMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.emulation.control.v2.Rtc/SendJsepMessage',
            rtc__service__v2__pb2.SendJsepMessageRequest.SerializeToString,
            rtc__service__v2__pb2.SendJsepMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveJsepMessageStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/android.emulation.control.v2.Rtc/ReceiveJsepMessageStream',
            rtc__service__v2__pb2.ReceiveJsepMessageRequest.SerializeToString,
            rtc__service__v2__pb2.ReceiveJsepMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveJsepMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.emulation.control.v2.Rtc/ReceiveJsepMessage',
            rtc__service__v2__pb2.ReceiveJsepMessageRequest.SerializeToString,
            rtc__service__v2__pb2.ReceiveJsepMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
