# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rtc_service_v2.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'rtc_service_v2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
import ice_config_pb2 as ice__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14rtc_service_v2.proto\x12\x1c\x61ndroid.emulation.control.v2\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a\x10ice_config.proto\"\x9e\x01\n\x10RtcStreamRequest\x12%\n\x07payload\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12M\n\x11ice_server_config\x18\x02 \x01(\x0b\x32-.android.emulation.control.v2.IceServerConfigH\x00\x88\x01\x01\x42\x14\n\x12_ice_server_config\"A\n\x11RtcStreamResponse\x12,\n\x02id\x18\x01 \x01(\x0b\x32 .android.emulation.control.v2.Id\"Q\n\x16SendJsepMessageRequest\x12\x37\n\x08jsep_msg\x18\x01 \x01(\x0b\x32%.android.emulation.control.v2.JsepMsg\"\x19\n\x17SendJsepMessageResponse\"I\n\x19ReceiveJsepMessageRequest\x12,\n\x02id\x18\x01 \x01(\x0b\x32 .android.emulation.control.v2.Id\"U\n\x1aReceiveJsepMessageResponse\x12\x37\n\x08jsep_msg\x18\x01 \x01(\x0b\x32%.android.emulation.control.v2.JsepMsg\"\x12\n\x02Id\x12\x0c\n\x04guid\x18\x01 \x01(\t\"H\n\x07JsepMsg\x12,\n\x02id\x18\x01 \x01(\x0b\x32 .android.emulation.control.v2.Id\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9f\x04\n\x03Rtc\x12u\n\x10RequestRtcStream\x12..android.emulation.control.v2.RtcStreamRequest\x1a/.android.emulation.control.v2.RtcStreamResponse\"\x00\x12\x80\x01\n\x0fSendJsepMessage\x12\x34.android.emulation.control.v2.SendJsepMessageRequest\x1a\x35.android.emulation.control.v2.SendJsepMessageResponse\"\x00\x12\x91\x01\n\x18ReceiveJsepMessageStream\x12\x37.android.emulation.control.v2.ReceiveJsepMessageRequest\x1a\x38.android.emulation.control.v2.ReceiveJsepMessageResponse\"\x00\x30\x01\x12\x89\x01\n\x12ReceiveJsepMessage\x12\x37.android.emulation.control.v2.ReceiveJsepMessageRequest\x1a\x38.android.emulation.control.v2.ReceiveJsepMessageResponse\"\x00\x42&\n\x1c\x63om.android.emulator.controlP\x01\xa2\x02\x03\x41\x45\x43\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rtc_service_v2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.android.emulator.controlP\001\242\002\003AEC'
  _globals['_RTCSTREAMREQUEST']._serialized_start=129
  _globals['_RTCSTREAMREQUEST']._serialized_end=287
  _globals['_RTCSTREAMRESPONSE']._serialized_start=289
  _globals['_RTCSTREAMRESPONSE']._serialized_end=354
  _globals['_SENDJSEPMESSAGEREQUEST']._serialized_start=356
  _globals['_SENDJSEPMESSAGEREQUEST']._serialized_end=437
  _globals['_SENDJSEPMESSAGERESPONSE']._serialized_start=439
  _globals['_SENDJSEPMESSAGERESPONSE']._serialized_end=464
  _globals['_RECEIVEJSEPMESSAGEREQUEST']._serialized_start=466
  _globals['_RECEIVEJSEPMESSAGEREQUEST']._serialized_end=539
  _globals['_RECEIVEJSEPMESSAGERESPONSE']._serialized_start=541
  _globals['_RECEIVEJSEPMESSAGERESPONSE']._serialized_end=626
  _globals['_ID']._serialized_start=628
  _globals['_ID']._serialized_end=646
  _globals['_JSEPMSG']._serialized_start=648
  _globals['_JSEPMSG']._serialized_end=720
  _globals['_RTC']._serialized_start=723
  _globals['_RTC']._serialized_end=1266
# @@protoc_insertion_point(module_scope)
